"""Small helpers shared across the mock providers.

Everything here exists to keep provider output deterministic: the same
topic string must always produce the same ids and the same timestamps, so
two `generate()` calls with identical input produce byte-identical packages
(chronicle_phase_c_adjusted_plan.md §8's determinism requirement).
"""

import re

# Fixed sentinel used for every generatedAt/dateOfSource/eventTime the mock
# providers emit. Real wall-clock timestamps would break determinism across
# runs; a real generation pipeline (Phase D+) will thread the actual
# RunRecord.createdAt through instead once that matters.
SENTINEL_DATETIME = "2000-01-01T00:00:00Z"
SENTINEL_DATE = "2000-01-01"

MOCK_CONTENT_WARNING = (
    "This package is entirely synthetic mock content generated by Phase C2's "
    "deterministic pipeline — it is not real historical scholarship and must "
    "never be treated as such."
)


def slugify(topic: str) -> str:
    lowered = topic.strip().lower()
    slug = re.sub(r"[^a-z0-9]+", "-", lowered).strip("-")
    return slug or "untitled"
